apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - general.yaml
  - jwt-keys.yaml

secretGenerator:
  - name: auth-tls
    namespace: auth
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key
