apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - grafana
  - kube-state-metrics
  - kafka
  - loki
  - node-exporter
  - prometheus
  - namespace.yaml
