apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: infra
data:
  KAFKA_NODE_ID: "1"
  CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://127.0.0.1:29093"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@127.0.0.1:29093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka.infra.svc.cluster.local:9092"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"


