apiVersion: v1
kind: ConfigMap
metadata:
  name: app-general
  namespace: auth
data:
  APP_ENV: "prod"
  DEFAULT_URI: "https://auth.local"
  REDIS_URL: "redis://redis:6379?timeout=1.0"
  KAFKA_BROKERS: "kafka.infra.svc.cluster.local:9092"
  KAFKA_TOPIC: "user-events"
  JWT_SECRET_KEY: "/var/www/app/config/jwt/private.pem"
  JWT_PUBLIC_KEY: "/var/www/app/config/jwt/public.pem"
  CORS_ALLOW_ORIGIN: "^https?://(web\\.local)(:[0-9]+)?$"
  UID: "1000"
  GID: "1000"
