apiVersion: v1
kind: ConfigMap
metadata:
  name: app-general
  namespace: auth
data:
  APP_ENV: "prod"
  DEFAULT_URI: "https://auth.local"
  REDIS_URL: "redis://redis:6379?timeout=1.0"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPIC: "user-events"
  JWT_SECRET_KEY: "/var/www/app/config/jwt/private.pem"
  JWT_PUBLIC_KEY: "/var/www/app/config/jwt/public.pem"
  UID: "1000"
  GID: "1000"
