apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: auth
data:
  default.conf: |
    server {
        listen 80;
        server_name auth.local;
        root /var/www/app/public;
        index index.php;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_index index.php;
        }
    }
