apiVersion: v1
kind: ConfigMap
metadata:
  name: phpfpm-conf
  namespace: auth
data:
  www.conf: |
    [www]
    user = appuser
    group = appuser
    listen = 9000
    pm = dynamic
    pm.max_children = 5
    pm.start_servers = 2
    pm.min_spare_servers = 1
    pm.max_spare_servers = 3

    ; Enable status page
    pm.status_path = /status
